### ISSUE TITLE
showing a progress bar/time estimate while pinsearch functions are running

### ISSUE THREAD

**Issue by meltemozcan** [marklhc/pinsearch#5]

**Comment by marklhc** [comment]
@meltemozcan could you try testing the added option `progress = TRUE` from the master branch? Just a crude implementation and let me know your thoughts. Thanks!

**Comment by meltemozcan** [comment]
@marklhc This looks great! I quite like that you broke it up into multiple progress bars for different goals so that the user gets an idea of what is happening under the hood.

One minor suggestion/idea would be to include in the messages the total number of tasks and the order of the current task so that there is a better understanding of the overall progress (e.g., in the example in the screenshot below I had specified `type = residuals` so we would have 3 progress bars for the three steps. The three messages then be something like the following: "[1/3] Searching for loadings noninvariance", "[2/3] Searching for intercepts noninvariance", and "[3/3] Searching for residuals noninvariance"). What do you think?

<img width="438" alt="Screenshot 2023-03-03 at 12 18 29 PM" src="https://user-images.githubusercontent.com/56315566/222822211-2f3d03d7-37aa-41f8-b59e-04f4cfd8df8a.png">

**Comment by marklhc** [comment]
﻿Forgot to reply, but changes have been made.Mark LaiOn Mar 3, 2023, at 12:33 PM, Meltem Ozcan ***@***.***> wrote:﻿
@marklhc This looks great! I quite like that you broke it up into multiple progress bars for different goals so that the user gets an idea of what is happening under the hood.
One minor suggestion/idea would be to include in the messages the total number of tasks and the order of the current task so that there is a better understanding of the overall progress (e.g., in the example in the screenshot below I had specified type = residuals so we would have 3 progress bars for the three steps. The three messages then be something like the following: "[1/3] Searching for loadings noninvariance", "[2/3] Searching for intercepts noninvariance", and "[3/3] Searching for residuals noninvariance"). What do you think?
